<?php

namespace Modules\AetherEngine\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\AetherEngine\Models\AetherExercise;

class AetherExerciseSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->exercises() as $exercise) {
            AetherExercise::query()->updateOrCreate(
                ['slug' => $exercise['slug']],
                $exercise,
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function exercises(): array
    {
        return [
            // ── QUADS ─────────────────────────────────────────────────────────────
            [
                'slug' => 'barbell-squat',
                'name' => 'Barbell Back Squat',
                'muscle_group' => 'quads',
                'equipment_required' => ['barbell'],
                'difficulty' => 3,
                'instructions' => 'Brace core and take a deep breath before descending. Sit hips back and down, keeping chest tall. Drive knees out over toes. Squat to at least parallel. Drive through the whole foot to stand.',
                'contraindications' => ['knee', 'lower_back'],
                'alternative_slugs' => ['goblet-squat', 'leg-press'],
                'rpe_range' => '7-8',
                'tempo' => '3-1-2-0',
                'default_weight_beginner_kg' => 40.0,
                'default_weight_intermediate_kg' => 80.0,
                'default_weight_advanced_kg' => 120.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/barbell-full-squat',
            ],
            [
                'slug' => 'goblet-squat',
                'name' => 'Goblet Squat',
                'muscle_group' => 'quads',
                'equipment_required' => ['dumbbell', 'kettlebell'],
                'difficulty' => 2,
                'instructions' => 'Hold weight at chest height with both hands. Feet shoulder-width, toes slightly out. Squat with an upright torso, elbows tracking inside knees. Drive through heels to stand.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['bodyweight-squat'],
                'rpe_range' => '6-7',
                'tempo' => '3-1-2-0',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 32.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'quads/dumbbell-goblet-squat',
            ],
            [
                'slug' => 'leg-press',
                'name' => 'Leg Press',
                'muscle_group' => 'quads',
                'equipment_required' => ['machine'],
                'difficulty' => 2,
                'instructions' => 'Place feet shoulder-width at mid-platform. Lower platform with control until knees reach 90°. Do not lock knees at the top. Keep lower back pressed into the pad throughout.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['goblet-squat'],
                'rpe_range' => '6-7',
                'tempo' => '3-0-2-0',
                'default_weight_beginner_kg' => 40.0,
                'default_weight_intermediate_kg' => 100.0,
                'default_weight_advanced_kg' => 160.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/sled-45-leg-press',
            ],
            [
                'slug' => 'walking-lunge',
                'name' => 'Walking Lunge',
                'muscle_group' => 'quads',
                'equipment_required' => ['dumbbell', 'bodyweight'],
                'difficulty' => 2,
                'instructions' => 'Take a long stride forward, lower back knee toward floor. Front knee tracks over toes but does not pass them. Push through front heel to step forward. Keep torso upright throughout.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['step-up'],
                'rpe_range' => '6-7',
                'tempo' => '2-0-1-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 12.0,
                'default_weight_advanced_kg' => 22.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/walking-lunge',
            ],
            [
                'slug' => 'step-up',
                'name' => 'Step-Up',
                'muscle_group' => 'quads',
                'equipment_required' => ['dumbbell', 'bench'],
                'difficulty' => 2,
                'instructions' => 'Place entire foot on box or bench. Drive through the whole foot to extend the hip and knee. Step down with control. Complete all reps on one leg before switching.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['walking-lunge'],
                'rpe_range' => '6-7',
                'tempo' => '2-0-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 12.0,
                'default_weight_advanced_kg' => 22.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/dumbbell-step-up',
            ],
            [
                'slug' => 'band-squat',
                'name' => 'Banded Squat',
                'muscle_group' => 'quads',
                'equipment_required' => ['band'],
                'difficulty' => 1,
                'instructions' => 'Stand on band, hold handles at shoulders. Perform a squat with tension throughout the movement — the band adds resistance at the top. Keep an upright torso.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['bodyweight-squat'],
                'rpe_range' => '5-6',
                'tempo' => '3-1-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
            [
                'slug' => 'bodyweight-squat',
                'name' => 'Bodyweight Squat',
                'muscle_group' => 'quads',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Feet flat on floor, slightly wider than shoulder-width. Sit hips back and down, chest up. Knees track toes. Drive through heels to stand. Great for warm-up or high-rep conditioning.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['band-squat'],
                'rpe_range' => '5-6',
                'tempo' => '3-0-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],

            // ── HAMSTRINGS ────────────────────────────────────────────────────────
            [
                'slug' => 'romanian-deadlift',
                'name' => 'Romanian Deadlift',
                'muscle_group' => 'hamstrings',
                'equipment_required' => ['barbell', 'dumbbell'],
                'difficulty' => 3,
                'instructions' => 'Stand with hips-width stance. Hinge at hips keeping back flat, bar stays close to legs. Lower until you feel a stretch in hamstrings (typically mid-shin). Drive hips forward to stand, squeezing glutes at top.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['hip-thrust'],
                'rpe_range' => '7-8',
                'tempo' => '3-1-1-0',
                'default_weight_beginner_kg' => 30.0,
                'default_weight_intermediate_kg' => 60.0,
                'default_weight_advanced_kg' => 100.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/barbell-romanian-deadlift',
            ],
            [
                'slug' => 'leg-curl',
                'name' => 'Lying Leg Curl',
                'muscle_group' => 'hamstrings',
                'equipment_required' => ['machine'],
                'difficulty' => 2,
                'instructions' => 'Lie face down on machine, pad resting just above heels. Curl heels toward glutes using a controlled 2-second eccentric. Avoid lifting hips. Pause briefly at peak contraction.',
                'contraindications' => [],
                'alternative_slugs' => ['romanian-deadlift'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 40.0,
                'default_weight_advanced_kg' => 60.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'hamstrings/lever-lying-leg-curl',
            ],

            // ── GLUTES ────────────────────────────────────────────────────────────
            [
                'slug' => 'hip-thrust',
                'name' => 'Hip Thrust',
                'muscle_group' => 'glutes',
                'equipment_required' => ['barbell', 'bench'],
                'difficulty' => 2,
                'instructions' => 'Sit against a bench with barbell across hips. Plant feet flat, shin perpendicular to floor. Drive hips up until torso is parallel to floor. Squeeze glutes hard at the top for 1 second. Lower with control.',
                'contraindications' => [],
                'alternative_slugs' => ['glute-bridge'],
                'rpe_range' => '7-8',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 60.0,
                'default_weight_advanced_kg' => 100.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/barbell-glute-bridge',
            ],
            [
                'slug' => 'glute-bridge',
                'name' => 'Glute Bridge',
                'muscle_group' => 'glutes',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Lie on back, knees bent, feet flat. Push through heels to lift hips until body is a straight line from shoulders to knees. Squeeze glutes at top. Avoid hyperextending the lower back.',
                'contraindications' => [],
                'alternative_slugs' => ['hip-thrust'],
                'rpe_range' => '5-6',
                'tempo' => '2-2-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 50.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/barbell-glute-bridge',
            ],

            // ── CALVES ────────────────────────────────────────────────────────────
            [
                'slug' => 'calf-raise',
                'name' => 'Standing Calf Raise',
                'muscle_group' => 'calves',
                'equipment_required' => ['machine', 'dumbbell'],
                'difficulty' => 1,
                'instructions' => 'Stand on edge of step or flat ground. Rise onto toes with a full contraction at the top — hold 1 second. Lower heels slowly for a full stretch at the bottom. Avoid bouncing.',
                'contraindications' => ['ankle'],
                'alternative_slugs' => [],
                'rpe_range' => '6-7',
                'tempo' => '2-1-2-1',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 60.0,
                'default_weight_advanced_kg' => 100.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'calves/barbell-standing-calf-raise',
            ],

            // ── CHEST ─────────────────────────────────────────────────────────────
            [
                'slug' => 'bench-press',
                'name' => 'Barbell Bench Press',
                'muscle_group' => 'chest',
                'equipment_required' => ['barbell', 'bench'],
                'difficulty' => 3,
                'instructions' => 'Retract and depress shoulder blades into bench. Grip slightly wider than shoulder-width. Lower bar to lower chest in a slight arc. Press back up, keeping elbows at 45–75°. Do not bounce bar off chest.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['dumbbell-press', 'push-up'],
                'rpe_range' => '7-8',
                'tempo' => '3-1-2-0',
                'default_weight_beginner_kg' => 30.0,
                'default_weight_intermediate_kg' => 60.0,
                'default_weight_advanced_kg' => 100.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'pectorals/barbell-bench-press',
            ],
            [
                'slug' => 'dumbbell-press',
                'name' => 'Dumbbell Bench Press',
                'muscle_group' => 'chest',
                'equipment_required' => ['dumbbell', 'bench'],
                'difficulty' => 2,
                'instructions' => 'Hold dumbbells with neutral wrists above chest. Lower with control until elbows are slightly below bench. Press up and slightly in. Full ROM allows greater chest stretch than barbell variation.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['push-up'],
                'rpe_range' => '6-7',
                'tempo' => '3-0-2-0',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 35.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'pectorals/dumbbell-bench-press',
            ],
            [
                'slug' => 'incline-dumbbell-press',
                'name' => 'Incline Dumbbell Press',
                'muscle_group' => 'chest',
                'equipment_required' => ['dumbbell', 'bench'],
                'difficulty' => 2,
                'instructions' => 'Set bench to 30–45°. Press dumbbells from shoulder height overhead. Focus on upper chest contraction. Keep core tight and lower back touching the bench. Do not flare elbows excessively.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['push-up'],
                'rpe_range' => '6-7',
                'tempo' => '3-0-2-0',
                'default_weight_beginner_kg' => 8.0,
                'default_weight_intermediate_kg' => 18.0,
                'default_weight_advanced_kg' => 30.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'pectorals/barbell-incline-bench-press',
            ],
            [
                'slug' => 'push-up',
                'name' => 'Push-Up',
                'muscle_group' => 'chest',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Maintain a rigid plank from head to heels. Hands slightly wider than shoulders. Lower chest to 1–2 cm from floor. Press back up to full arm extension. Squeeze chest at the top.',
                'contraindications' => ['wrist', 'shoulder'],
                'alternative_slugs' => ['dumbbell-press'],
                'rpe_range' => '5-7',
                'tempo' => '3-0-1-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'pectorals/push-up',
            ],
            [
                'slug' => 'cable-fly',
                'name' => 'Cable Fly',
                'muscle_group' => 'chest',
                'equipment_required' => ['cable'],
                'difficulty' => 2,
                'instructions' => 'Stand between cables set at upper chest height. Step forward, slight forward lean. Bring handles together in a wide arc with a slight elbow bend. Squeeze chest at midline. Return with control.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['push-up'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 5.0,
                'default_weight_intermediate_kg' => 10.0,
                'default_weight_advanced_kg' => 15.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'pectorals/cable-incline-fly',
            ],

            // ── BACK ──────────────────────────────────────────────────────────────
            [
                'slug' => 'conventional-deadlift',
                'name' => 'Conventional Deadlift',
                'muscle_group' => 'back',
                'equipment_required' => ['barbell'],
                'difficulty' => 4,
                'instructions' => 'Bar over mid-foot. Grip just outside shins. Hinge to bar maintaining neutral spine. Push floor away rather than pulling bar up. Drive hips through at top. Lower with control — do not drop the bar.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['romanian-deadlift'],
                'rpe_range' => '8-9',
                'tempo' => '1-1-3-0',
                'default_weight_beginner_kg' => 40.0,
                'default_weight_intermediate_kg' => 100.0,
                'default_weight_advanced_kg' => 150.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/barbell-deadlift',
            ],
            [
                'slug' => 'pull-up',
                'name' => 'Pull-Up',
                'muscle_group' => 'back',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 4,
                'instructions' => 'Hang with full shoulder engagement (active hang). Drive elbows down toward hips to initiate the pull. Chin clears the bar at the top. Lower with control over 3 seconds. Use a resistance band to assist if needed.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['lat-pulldown', 'inverted-row'],
                'rpe_range' => '7-9',
                'tempo' => '2-0-3-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'biceps/biceps-pull-up',
            ],
            [
                'slug' => 'lat-pulldown',
                'name' => 'Lat Pulldown',
                'muscle_group' => 'back',
                'equipment_required' => ['cable', 'machine'],
                'difficulty' => 2,
                'instructions' => 'Grip bar slightly wider than shoulder-width. Lean back slightly and initiate pull by depressing shoulders. Drive elbows down toward hips. Bar reaches upper chest. Avoid shrugging and using momentum.',
                'contraindications' => [],
                'alternative_slugs' => ['pull-up'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 45.0,
                'default_weight_advanced_kg' => 70.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'lats/cable-lat-pulldown-full-range-of-motion',
            ],
            [
                'slug' => 'barbell-row',
                'name' => 'Barbell Row',
                'muscle_group' => 'back',
                'equipment_required' => ['barbell'],
                'difficulty' => 3,
                'instructions' => 'Hinge torso to about 45°. Pull bar to lower ribs — not upper chest. Lead with elbows, retract scapulae at top. Keep core braced and back flat. Control the eccentric phase fully.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['dumbbell-row'],
                'rpe_range' => '7-8',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 30.0,
                'default_weight_intermediate_kg' => 60.0,
                'default_weight_advanced_kg' => 90.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'upper-back/barbell-bent-over-row',
            ],
            [
                'slug' => 'dumbbell-row',
                'name' => 'Single-Arm Dumbbell Row',
                'muscle_group' => 'back',
                'equipment_required' => ['dumbbell', 'bench'],
                'difficulty' => 2,
                'instructions' => 'Brace hand and knee on bench. Let arm hang fully. Pull elbow straight back to hip — not out to the side. Pause at the top. Lower the dumbbell with a 3-second eccentric for maximum lat stretch.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['inverted-row'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 22.0,
                'default_weight_advanced_kg' => 36.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'upper-back/dumbbell-bent-over-row',
            ],
            [
                'slug' => 'inverted-row',
                'name' => 'Inverted Row',
                'muscle_group' => 'back',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 2,
                'instructions' => 'Set bar at waist height. Hang below it with arms straight. Keep body rigid and pull chest to bar. Retract scapulae fully at the top. Easier by bending knees, harder by elevating feet.',
                'contraindications' => [],
                'alternative_slugs' => ['lat-pulldown'],
                'rpe_range' => '5-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'upper-back/inverted-row-bent-knees',
            ],
            [
                'slug' => 'seated-cable-row',
                'name' => 'Seated Cable Row',
                'muscle_group' => 'back',
                'equipment_required' => ['cable'],
                'difficulty' => 2,
                'instructions' => 'Sit tall with a slight hip hinge. Pull handle to lower ribs while retracting scapulae. Do not lean back excessively. Return with a controlled stretch, allowing shoulder blades to protract fully.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['dumbbell-row'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 45.0,
                'default_weight_advanced_kg' => 70.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'upper-back/cable-seated-row',
            ],
            [
                'slug' => 'band-row',
                'name' => 'Banded Row',
                'muscle_group' => 'back',
                'equipment_required' => ['band'],
                'difficulty' => 1,
                'instructions' => 'Anchor band at mid-torso height. Step back to create tension. Pull elbows back, squeezing shoulder blades together. Hold for 1 second. Return with control to a full stretch position.',
                'contraindications' => [],
                'alternative_slugs' => ['inverted-row'],
                'rpe_range' => '5-6',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'upper-back/bodyweight-standing-one-arm-row',
            ],

            // ── SHOULDERS ─────────────────────────────────────────────────────────
            [
                'slug' => 'overhead-press',
                'name' => 'Overhead Press',
                'muscle_group' => 'shoulders',
                'equipment_required' => ['barbell', 'dumbbell'],
                'difficulty' => 3,
                'instructions' => 'Brace core and ribs down. Press bar or dumbbells straight overhead. At the top, shrug traps slightly and lock out elbows. Lower to collarbone height. Avoid excessive lumbar arch.',
                'contraindications' => ['shoulder', 'lower_back'],
                'alternative_slugs' => ['lateral-raise'],
                'rpe_range' => '7-8',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 20.0,
                'default_weight_intermediate_kg' => 40.0,
                'default_weight_advanced_kg' => 70.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'delts/barbell-seated-overhead-press',
            ],
            [
                'slug' => 'lateral-raise',
                'name' => 'Lateral Raise',
                'muscle_group' => 'shoulders',
                'equipment_required' => ['dumbbell'],
                'difficulty' => 1,
                'instructions' => 'Slight forward lean at hips. Lead with elbows, not wrists. Raise arms to shoulder height — thumbs slightly lower than pinkies. Pause 1 second at top. Lower slowly over 3 seconds.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['band-pull-apart'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 4.0,
                'default_weight_intermediate_kg' => 8.0,
                'default_weight_advanced_kg' => 14.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'delts/dumbbell-lateral-raise',
            ],
            [
                'slug' => 'face-pull',
                'name' => 'Face Pull',
                'muscle_group' => 'shoulders',
                'equipment_required' => ['cable', 'band'],
                'difficulty' => 2,
                'instructions' => 'Set cable or band at upper-face height. Pull rope to forehead, externally rotating at end range — "hands behind ears". Great for rear delt and rotator cuff health. Control the return fully.',
                'contraindications' => [],
                'alternative_slugs' => ['band-pull-apart'],
                'rpe_range' => '5-6',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 8.0,
                'default_weight_intermediate_kg' => 15.0,
                'default_weight_advanced_kg' => 25.0,
            ],
            [
                'slug' => 'band-pull-apart',
                'name' => 'Band Pull-Apart',
                'muscle_group' => 'shoulders',
                'equipment_required' => ['band'],
                'difficulty' => 1,
                'instructions' => 'Hold band at chest height, arms extended forward. Pull band apart until it touches your chest, squeezing rear delts and rhomboids. Return with control. Excellent shoulder health and warm-up exercise.',
                'contraindications' => [],
                'alternative_slugs' => ['face-pull'],
                'rpe_range' => '4-5',
                'tempo' => '2-1-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],

            // ── BICEPS ────────────────────────────────────────────────────────────
            [
                'slug' => 'barbell-curl',
                'name' => 'Barbell Curl',
                'muscle_group' => 'biceps',
                'equipment_required' => ['barbell'],
                'difficulty' => 2,
                'instructions' => 'Stand with hips-width stance, elbows tucked at sides. Curl bar up in a smooth arc. Squeeze biceps at top. Lower with a 3-second eccentric — do not swing or use momentum.',
                'contraindications' => ['wrist'],
                'alternative_slugs' => ['hammer-curl'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 15.0,
                'default_weight_intermediate_kg' => 30.0,
                'default_weight_advanced_kg' => 50.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'biceps/barbell-curl',
            ],
            [
                'slug' => 'hammer-curl',
                'name' => 'Hammer Curl',
                'muscle_group' => 'biceps',
                'equipment_required' => ['dumbbell'],
                'difficulty' => 1,
                'instructions' => 'Neutral grip (palms facing each other). Curl dumbbells without rotating the wrist. Hits brachialis and brachioradialis in addition to biceps. Lower with a slow 3-second eccentric.',
                'contraindications' => ['wrist'],
                'alternative_slugs' => ['band-curl'],
                'rpe_range' => '5-7',
                'tempo' => '2-0-3-0',
                'default_weight_beginner_kg' => 8.0,
                'default_weight_intermediate_kg' => 15.0,
                'default_weight_advanced_kg' => 24.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'biceps/dumbbell-hammer-curl',
            ],
            [
                'slug' => 'band-curl',
                'name' => 'Band Biceps Curl',
                'muscle_group' => 'biceps',
                'equipment_required' => ['band'],
                'difficulty' => 1,
                'instructions' => 'Stand on band, curl handles up with supinated grip. The band provides constant tension — hardest at full contraction. Lower slowly. Great finisher or when no dumbbells are available.',
                'contraindications' => [],
                'alternative_slugs' => ['hammer-curl'],
                'rpe_range' => '5-6',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'biceps/band-alternating-biceps-curl',
            ],

            // ── TRICEPS ───────────────────────────────────────────────────────────
            [
                'slug' => 'tricep-pushdown',
                'name' => 'Cable Triceps Pushdown',
                'muscle_group' => 'triceps',
                'equipment_required' => ['cable'],
                'difficulty' => 1,
                'instructions' => 'Set cable at face height. Pin elbows at sides — they should not move. Push handle straight down to full lockout. Squeeze triceps at the bottom. Return handle up to 90° with control.',
                'contraindications' => ['elbow'],
                'alternative_slugs' => ['diamond-push-up'],
                'rpe_range' => '6-7',
                'tempo' => '2-0-2-1',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 35.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'triceps/cable-one-arm-tricep-pushdown',
            ],
            [
                'slug' => 'skull-crusher',
                'name' => 'Skull Crusher',
                'muscle_group' => 'triceps',
                'equipment_required' => ['barbell', 'dumbbell'],
                'difficulty' => 3,
                'instructions' => 'Lie on bench, arms extended over chest. Hinge ONLY at elbows to lower bar to forehead. Elbows stay stationary and pointed at the ceiling. Press back to full extension. Use a moderate weight to protect elbows.',
                'contraindications' => ['elbow', 'wrist'],
                'alternative_slugs' => ['tricep-pushdown'],
                'rpe_range' => '6-7',
                'tempo' => '3-0-2-0',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 25.0,
                'default_weight_advanced_kg' => 40.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'triceps/barbell-lying-triceps-extension-skull-crusher',
            ],
            [
                'slug' => 'diamond-push-up',
                'name' => 'Diamond Push-Up',
                'muscle_group' => 'triceps',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 2,
                'instructions' => 'Form a diamond with thumbs and index fingers. Elbows track back along the torso, not out to the sides. Lower chest to hands. Press back up, focusing on triceps extension. Harder than standard push-up.',
                'contraindications' => ['wrist'],
                'alternative_slugs' => ['tricep-pushdown'],
                'rpe_range' => '6-8',
                'tempo' => '3-0-1-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'triceps/diamond-push-up',
            ],

            // ── CORE ──────────────────────────────────────────────────────────────
            [
                'slug' => 'plank',
                'name' => 'Front Plank',
                'muscle_group' => 'core',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Forearms on floor, elbows under shoulders. Brace core as if about to take a punch. Think "ribs to pelvis." Keep hips level — no sagging or hiking. Breathe steadily throughout the hold.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['dead-bug'],
                'rpe_range' => '5-6',
                'tempo' => 'hold',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'abs/weighted-front-plank',
            ],
            [
                'slug' => 'dead-bug',
                'name' => 'Dead Bug',
                'muscle_group' => 'core',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Lie on back, lower back pressed into floor. Arms up, knees at 90°. Slowly extend opposite arm and leg toward floor — keep lower back contact. Return and switch. Never let lower back arch away from floor.',
                'contraindications' => [],
                'alternative_slugs' => ['plank'],
                'rpe_range' => '4-5',
                'tempo' => '3-0-3-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'abs/dead-bug',
            ],
            [
                'slug' => 'hanging-knee-raise',
                'name' => 'Hanging Knee Raise',
                'muscle_group' => 'core',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 3,
                'instructions' => 'Hang from bar with active shoulders (no passive hang). Curl knees toward chest using posterior pelvic tilt — do not just swing hips. Lower with control. Advanced: extend legs fully for hanging leg raise.',
                'contraindications' => ['lower_back', 'shoulder'],
                'alternative_slugs' => ['dead-bug'],
                'rpe_range' => '6-7',
                'tempo' => '2-1-3-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
            [
                'slug' => 'pallof-press',
                'name' => 'Pallof Press',
                'muscle_group' => 'core',
                'equipment_required' => ['cable', 'band'],
                'difficulty' => 2,
                'instructions' => 'Stand sideways to cable/band, feet shoulder-width. Hold handle at chest. Press out to full extension — resist the rotational pull. Hold for 2 seconds, return. Keep hips and shoulders square throughout.',
                'contraindications' => [],
                'alternative_slugs' => ['plank'],
                'rpe_range' => '5-6',
                'tempo' => '2-2-2-0',
                'default_weight_beginner_kg' => 5.0,
                'default_weight_intermediate_kg' => 10.0,
                'default_weight_advanced_kg' => 20.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'abs/band-horizontal-pallof-press',
            ],

            // ── FULL BODY ─────────────────────────────────────────────────────────
            [
                'slug' => 'burpee',
                'name' => 'Burpee',
                'muscle_group' => 'full_body',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 3,
                'instructions' => 'From standing, squat and place hands on floor. Jump or step feet back to plank. Perform a push-up (optional). Jump or step feet to hands. Jump up with arms overhead. Scale by stepping instead of jumping.',
                'contraindications' => ['knee', 'wrist'],
                'alternative_slugs' => ['mountain-climber'],
                'rpe_range' => '7-8',
                'tempo' => 'X-0-1-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'cardio/burpee',
            ],
            [
                'slug' => 'mountain-climber',
                'name' => 'Mountain Climber',
                'muscle_group' => 'full_body',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 2,
                'instructions' => 'Start in a plank position. Drive one knee toward chest, then quickly switch feet. Keep hips level — no bouncing. Core braced throughout. Can be performed slowly for core focus or fast for conditioning.',
                'contraindications' => ['wrist'],
                'alternative_slugs' => ['jumping-jack'],
                'rpe_range' => '6-7',
                'tempo' => 'X-0-X-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'cardio/mountain-climber',
            ],
            [
                'slug' => 'kettlebell-swing',
                'name' => 'Kettlebell Swing',
                'muscle_group' => 'full_body',
                'equipment_required' => ['kettlebell'],
                'difficulty' => 3,
                'instructions' => 'Hinge powerfully at hips to generate momentum. Arms are relaxed — the hip drive powers the swing. Squeeze glutes hard at the top. Let the bell fall back between legs in a controlled arc. Do not squat.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['hip-thrust'],
                'rpe_range' => '7-8',
                'tempo' => 'X-0-X-0',
                'default_weight_beginner_kg' => 12.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 32.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'glutes/kettlebell-swing',
            ],
            [
                'slug' => 'farmer-carry',
                'name' => 'Farmer Carry',
                'muscle_group' => 'full_body',
                'equipment_required' => ['dumbbell', 'kettlebell'],
                'difficulty' => 2,
                'instructions' => 'Hold heavy weights at sides. Stand tall — avoid lateral lean. Walk with a strong, steady gait for prescribed distance or time. Great for grip strength, core stability, and cardiovascular conditioning.',
                'contraindications' => ['lower_back'],
                'alternative_slugs' => ['plank'],
                'rpe_range' => '6-7',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 10.0,
                'default_weight_intermediate_kg' => 20.0,
                'default_weight_advanced_kg' => 32.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'quads/farmers-walk',
            ],
            [
                'slug' => 'sled-push',
                'name' => 'Sled Push',
                'muscle_group' => 'full_body',
                'equipment_required' => ['machine'],
                'difficulty' => 3,
                'instructions' => 'Lean forward at 45°, arms extended to sled handles. Drive powerfully through legs with short, powerful strides. Keep hips low and core braced. Excellent metabolic conditioning with minimal injury risk.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['walking-lunge'],
                'rpe_range' => '7-9',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 40.0,
                'default_weight_intermediate_kg' => 80.0,
                'default_weight_advanced_kg' => 120.0,
            ],

            // ── CARDIO ────────────────────────────────────────────────────────────
            [
                'slug' => 'jumping-jack',
                'name' => 'Jumping Jack',
                'muscle_group' => 'cardio',
                'equipment_required' => ['bodyweight'],
                'difficulty' => 1,
                'instructions' => 'Land softly with slightly bent knees on every jump. Keep a steady rhythm. Arms go fully overhead each rep. Great warm-up or conditioning exercise. Scale to step jacks if impact is an issue.',
                'contraindications' => ['knee', 'ankle'],
                'alternative_slugs' => ['jump-rope'],
                'rpe_range' => '5-6',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
            [
                'slug' => 'jump-rope',
                'name' => 'Jump Rope',
                'muscle_group' => 'cardio',
                'equipment_required' => ['cardio'],
                'difficulty' => 2,
                'instructions' => 'Wrists drive the rope rotation — not shoulders. Land on balls of feet with slightly bent knees. Keep jumps small (2–3 cm off ground). Start with 30-second intervals and build up duration progressively.',
                'contraindications' => ['ankle', 'knee'],
                'alternative_slugs' => ['jumping-jack'],
                'rpe_range' => '6-7',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
                'api_source' => 'exercise_gym_gifs_db',
                'api_external_id' => 'cardio/jump-rope',
            ],
            [
                'slug' => 'treadmill-run',
                'name' => 'Treadmill Run',
                'muscle_group' => 'cardio',
                'equipment_required' => ['cardio'],
                'difficulty' => 2,
                'instructions' => 'For LISS: maintain a conversational pace where you can speak in full sentences. For HIIT: alternate 30s hard / 90s easy. Do not hold handrails — this reduces calorie burn and proper form.',
                'contraindications' => ['knee', 'ankle'],
                'alternative_slugs' => ['outdoor-run'],
                'rpe_range' => '5-7',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
            [
                'slug' => 'outdoor-run',
                'name' => 'Outdoor Run',
                'muscle_group' => 'cardio',
                'equipment_required' => ['cardio'],
                'difficulty' => 2,
                'instructions' => 'Build aerobic base before increasing pace. Run on softer surfaces (grass, trails) to reduce joint impact. Use a heart rate monitor to stay in Zone 2 (65–75% max HR) for fat loss and endurance.',
                'contraindications' => ['knee', 'ankle'],
                'alternative_slugs' => ['jumping-jack'],
                'rpe_range' => '5-7',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
            [
                'slug' => 'bike-erg',
                'name' => 'Assault Bike',
                'muscle_group' => 'cardio',
                'equipment_required' => ['cardio', 'machine'],
                'difficulty' => 3,
                'instructions' => 'Use both arms and legs simultaneously for maximum calorie burn. For intervals: 20s all-out / 40s easy. The fan resistance increases naturally with output. Keep upright posture and drive with full leg extension.',
                'contraindications' => ['knee'],
                'alternative_slugs' => ['treadmill-run'],
                'rpe_range' => '7-9',
                'tempo' => 'continuous',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],

            // ── CHEST (BAND) ───────────────────────────────────────────────────────
            [
                'slug' => 'band-press',
                'name' => 'Banded Chest Press',
                'muscle_group' => 'chest',
                'equipment_required' => ['band'],
                'difficulty' => 1,
                'instructions' => 'Anchor band behind you at chest height. Step forward and press handles out with stable core. Constant tension means even the lockout is challenging. Great when no bench or dumbbells are available.',
                'contraindications' => ['shoulder'],
                'alternative_slugs' => ['push-up'],
                'rpe_range' => '5-6',
                'tempo' => '2-0-2-0',
                'default_weight_beginner_kg' => 0.0,
                'default_weight_intermediate_kg' => 0.0,
                'default_weight_advanced_kg' => 0.0,
            ],
        ];
    }
}
